# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ac18bfccf2f96d704b22a50adc1e81cbd51b5ed1a8e213c163c8d986e6aa68470788441f808fc5bc33a0d62b791c53d8d6a23bb0cd31d9b3278e18d4eab7295

test:
  secret_key_base: b30d83cdcbb6954392bb566642ae146f848633269508532e946854018792cf680089a716c97971747a5e93cb08c08bae3c7a9fc304f1c2819f8081a74641ea51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
